from typing import Any

COURSE_CURRICULUM: dict[str, Any] = {
    "id": "prompt-engineering-mastery",
    "title": "Prompt Engineering Mastery",
    "subtitle": "From Beginner to Industry Expert",
    "total_levels": 5,
    "estimated_total_hours": 120,
    "recommended_duration_weeks": 20,
    "description": (
        "A complete end-to-end curriculum for learning prompt engineering across consumer use-cases, "
        "technical systems, and enterprise-grade production workflows."
    ),
    "learning_outcomes": [
        "Design reliable prompts for reasoning, coding, creative work, and factual tasks.",
        "Build reusable prompting frameworks and evaluate prompt quality with measurable rubrics.",
        "Run A/B prompt experiments and optimize latency, quality, and cost.",
        "Design production prompt pipelines with guardrails, monitoring, and governance.",
        "Lead enterprise prompt strategy and mentor teams as an internal subject-matter expert.",
    ],
    "levels": [
        {
            "id": "level-1",
            "level": "Beginner",
            "title": "Prompt Fundamentals",
            "duration_weeks": 3,
            "outcome": "Write clear prompts with role, task, context, constraints, and format.",
            "modules": [
                {
                    "id": "l1m1",
                    "title": "Prompt Anatomy",
                    "objective": "Understand the core building blocks of high-quality prompts.",
                    "duration_hours": 6,
                    "checkpoint_project": "Create a reusable prompt template library for 5 common tasks.",
                    "lessons": [
                        {
                            "id": "l1m1-1",
                            "title": "What Makes a Prompt Work",
                            "what_you_learn": "Intent clarity, ambiguity reduction, and prompt failure patterns.",
                            "hands_on": "Rewrite 10 weak prompts into clear role-task-context prompts.",
                            "deliverable": "Before/after prompt revision sheet.",
                        },
                        {
                            "id": "l1m1-2",
                            "title": "Role + Goal + Constraints",
                            "what_you_learn": "How model behavior changes with explicit role and goals.",
                            "hands_on": "Design 3 role-based prompts for the same business scenario.",
                            "deliverable": "Role sensitivity comparison notes.",
                        },
                        {
                            "id": "l1m1-3",
                            "title": "Output Formatting",
                            "what_you_learn": "Control output shape with JSON, tables, bullets, and schemas.",
                            "hands_on": "Force model output to strict JSON for an onboarding workflow.",
                            "deliverable": "Schema-validated output prompt.",
                        },
                    ],
                    "review_questions": [
                        "Did you define a precise objective?",
                        "Can two different models interpret your prompt consistently?",
                        "Is the expected output format explicit and testable?",
                    ],
                },
                {
                    "id": "l1m2",
                    "title": "Zero-shot and Few-shot Prompting",
                    "objective": "Guide model behavior with examples and style anchors.",
                    "duration_hours": 7,
                    "checkpoint_project": "Build a few-shot prompt pack for customer support replies.",
                    "lessons": [
                        {
                            "id": "l1m2-1",
                            "title": "Zero-shot Baselines",
                            "what_you_learn": "How to benchmark prompts before optimization.",
                            "hands_on": "Create baseline prompts for summary, extraction, and classification.",
                            "deliverable": "Baseline quality report.",
                        },
                        {
                            "id": "l1m2-2",
                            "title": "Few-shot Demonstrations",
                            "what_you_learn": "Selecting high-signal examples and edge cases.",
                            "hands_on": "Craft 4-shot prompts for tone-consistent email generation.",
                            "deliverable": "Few-shot prompt bank.",
                        },
                        {
                            "id": "l1m2-3",
                            "title": "Instruction Hierarchy",
                            "what_you_learn": "Priority ordering when multiple constraints conflict.",
                            "hands_on": "Reorder instructions to optimize adherence for compliance writing.",
                            "deliverable": "Instruction priority rubric.",
                        },
                    ],
                    "review_questions": [
                        "Did examples represent edge cases?",
                        "Did output quality improve over zero-shot baseline?",
                        "Is style consistency stable across runs?",
                    ],
                },
                {
                    "id": "l1m3",
                    "title": "Prompt Debugging",
                    "objective": "Diagnose and fix weak responses systematically.",
                    "duration_hours": 5,
                    "checkpoint_project": "Debug a failing prompt suite and improve pass-rate by 30 percent.",
                    "lessons": [
                        {
                            "id": "l1m3-1",
                            "title": "Failure Taxonomy",
                            "what_you_learn": "Hallucinations, under-specification, and format drift.",
                            "hands_on": "Tag 20 bad outputs by failure category.",
                            "deliverable": "Prompt failure taxonomy board.",
                        },
                        {
                            "id": "l1m3-2",
                            "title": "Constraint Repair",
                            "what_you_learn": "Fixing vagueness with hard and soft constraints.",
                            "hands_on": "Apply iterative repair loops on 5 failure prompts.",
                            "deliverable": "Prompt repair changelog.",
                        },
                    ],
                    "review_questions": [
                        "Can you reproduce the failure reliably?",
                        "What was the single highest-impact fix?",
                        "How do you prevent regression in future prompt versions?",
                    ],
                },
            ],
            "capstone": "Launch a mini prompt playbook with 15 tested prompts for common workplace tasks.",
        },
        {
            "id": "level-2",
            "level": "Intermediate",
            "title": "Reasoning and Workflow Design",
            "duration_weeks": 4,
            "outcome": "Build prompts that guide multi-step reasoning and decision quality.",
            "modules": [
                {
                    "id": "l2m1",
                    "title": "Reasoning Control Techniques",
                    "objective": "Increase reliability for analytical and technical responses.",
                    "duration_hours": 8,
                    "checkpoint_project": "Create an analysis prompt that consistently produces assumption-aware recommendations.",
                    "lessons": [
                        {
                            "id": "l2m1-1",
                            "title": "Step Framing Without Overloading",
                            "what_you_learn": "Prompting for structured reasoning without token waste.",
                            "hands_on": "Design concise 4-step prompts for product strategy analysis.",
                            "deliverable": "Reasoning scaffold template.",
                        },
                        {
                            "id": "l2m1-2",
                            "title": "Assumption-first Prompting",
                            "what_you_learn": "Forcing explicit assumptions before recommendations.",
                            "hands_on": "Convert direct-answer prompts to assumption-first workflows.",
                            "deliverable": "Assumption checklist prompts.",
                        },
                        {
                            "id": "l2m1-3",
                            "title": "Trade-off Reasoning",
                            "what_you_learn": "How to request pros/cons and risk-aware options.",
                            "hands_on": "Generate three-option recommendations with decision criteria.",
                            "deliverable": "Decision matrix output template.",
                        },
                    ],
                    "review_questions": [
                        "Are assumptions explicit?",
                        "Does output compare alternatives objectively?",
                        "Are risks and unknowns clearly stated?",
                    ],
                },
                {
                    "id": "l2m2",
                    "title": "Domain Prompting",
                    "objective": "Adapt prompt patterns for coding, research, marketing, and operations.",
                    "duration_hours": 9,
                    "checkpoint_project": "Ship 4 domain-specific prompt packs with test scenarios.",
                    "lessons": [
                        {
                            "id": "l2m2-1",
                            "title": "Engineering Prompt Patterns",
                            "what_you_learn": "Design/debug/refactor prompt formats for developers.",
                            "hands_on": "Build a bug triage prompt that emits reproducible steps.",
                            "deliverable": "Engineering prompt card set.",
                        },
                        {
                            "id": "l2m2-2",
                            "title": "Business and Marketing Prompt Patterns",
                            "what_you_learn": "Audience-specific messaging and funnel-aware prompting.",
                            "hands_on": "Create persona-driven campaign copy prompts.",
                            "deliverable": "Marketing prompt matrix.",
                        },
                        {
                            "id": "l2m2-3",
                            "title": "Research and Synthesis Prompts",
                            "what_you_learn": "Evidence-oriented summary and extraction prompts.",
                            "hands_on": "Build a prompt to extract claims, evidence, and confidence.",
                            "deliverable": "Evidence synthesis template.",
                        },
                    ],
                    "review_questions": [
                        "Did you encode domain assumptions?",
                        "Is terminology consistent with target audience?",
                        "Can outputs be used directly with minimal edits?",
                    ],
                },
                {
                    "id": "l2m3",
                    "title": "Reusable Prompt Systems",
                    "objective": "Create modular prompt templates for teams.",
                    "duration_hours": 7,
                    "checkpoint_project": "Build team-ready prompt SOP with versioning standards.",
                    "lessons": [
                        {
                            "id": "l2m3-1",
                            "title": "Prompt Variables and Slots",
                            "what_you_learn": "Template parameters for scalable reuse.",
                            "hands_on": "Template a proposal-writing prompt with variable placeholders.",
                            "deliverable": "Parameterized prompt template.",
                        },
                        {
                            "id": "l2m3-2",
                            "title": "Versioning and Changelogs",
                            "what_you_learn": "How to evolve prompts safely over time.",
                            "hands_on": "Document v1 to v3 prompt changes with outcome metrics.",
                            "deliverable": "Prompt version registry.",
                        },
                    ],
                    "review_questions": [
                        "Can non-experts use your template correctly?",
                        "Are variable defaults safe and practical?",
                        "Do you track quality impact across versions?",
                    ],
                },
            ],
            "capstone": "Create a department-wide prompt handbook with workflows, examples, and QA checks.",
        },
        {
            "id": "level-3",
            "level": "Advanced",
            "title": "Evaluation and Optimization",
            "duration_weeks": 4,
            "outcome": "Measure prompt quality and optimize for quality-cost-latency trade-offs.",
            "modules": [
                {
                    "id": "l3m1",
                    "title": "Prompt Evaluation Frameworks",
                    "objective": "Quantify quality using objective and subjective metrics.",
                    "duration_hours": 10,
                    "checkpoint_project": "Design a prompt scorecard with weighted metrics.",
                    "lessons": [
                        {
                            "id": "l3m1-1",
                            "title": "Metric Design",
                            "what_you_learn": "Relevance, adherence, structure, hallucination risk, and usefulness.",
                            "hands_on": "Build rubric-based scoring for 3 prompt families.",
                            "deliverable": "Prompt evaluation rubric pack.",
                        },
                        {
                            "id": "l3m1-2",
                            "title": "Golden Datasets",
                            "what_you_learn": "Curating benchmark scenarios and expected outcomes.",
                            "hands_on": "Create 30 scenario dataset for prompt benchmarking.",
                            "deliverable": "Scenario benchmark dataset.",
                        },
                        {
                            "id": "l3m1-3",
                            "title": "Human + Automated Review",
                            "what_you_learn": "Combining heuristic checks with human judgment.",
                            "hands_on": "Run dual-review pipeline for A/B prompt outputs.",
                            "deliverable": "Evaluation protocol document.",
                        },
                    ],
                    "review_questions": [
                        "Are metrics aligned with business goals?",
                        "Can your benchmark detect regressions?",
                        "Do raters agree on scoring consistency?",
                    ],
                },
                {
                    "id": "l3m2",
                    "title": "A/B Testing and Prompt Experiments",
                    "objective": "Run controlled experiments and rank prompt variants.",
                    "duration_hours": 8,
                    "checkpoint_project": "Execute an A/B/C prompt experiment and publish insights.",
                    "lessons": [
                        {
                            "id": "l3m2-1",
                            "title": "Hypothesis-driven Prompt Testing",
                            "what_you_learn": "Designing controlled prompt experiments.",
                            "hands_on": "Write hypotheses for 5 prompt variants and expected impact.",
                            "deliverable": "Prompt experiment design sheet.",
                        },
                        {
                            "id": "l3m2-2",
                            "title": "Ranking and Winner Selection",
                            "what_you_learn": "Weighted scoring and tie-break strategy.",
                            "hands_on": "Score and rank outputs using multiple criteria.",
                            "deliverable": "Prompt leaderboard and analysis.",
                        },
                    ],
                    "review_questions": [
                        "Did you isolate one variable at a time?",
                        "Are sample sizes sufficient for confidence?",
                        "Is winner selection transparent and reproducible?",
                    ],
                },
                {
                    "id": "l3m3",
                    "title": "Cost and Latency Optimization",
                    "objective": "Balance quality with model cost and response speed.",
                    "duration_hours": 6,
                    "checkpoint_project": "Reduce token usage by 25 percent without quality drop.",
                    "lessons": [
                        {
                            "id": "l3m3-1",
                            "title": "Prompt Compression Techniques",
                            "what_you_learn": "How to shorten prompts while preserving intent.",
                            "hands_on": "Compress 10 long prompts and compare output quality.",
                            "deliverable": "Compressed prompt benchmark report.",
                        },
                        {
                            "id": "l3m3-2",
                            "title": "Model Routing Strategies",
                            "what_you_learn": "Route by complexity and confidence to optimize spend.",
                            "hands_on": "Design router rules for low/medium/high complexity tasks.",
                            "deliverable": "Routing policy definition.",
                        },
                    ],
                    "review_questions": [
                        "Which tokens are low-value and removable?",
                        "Where should heavy models be mandatory?",
                        "Did optimization hurt reliability?",
                    ],
                },
            ],
            "capstone": "Ship an optimization report with tested prompt variants and deployment recommendation.",
        },
        {
            "id": "level-4",
            "level": "Professional",
            "title": "Production Prompt Engineering",
            "duration_weeks": 5,
            "outcome": "Design production-safe prompt workflows with governance and monitoring.",
            "modules": [
                {
                    "id": "l4m1",
                    "title": "Guardrails and Safety",
                    "objective": "Prevent unsafe, biased, or policy-violating outputs.",
                    "duration_hours": 10,
                    "checkpoint_project": "Implement a safety prompt stack with refusal and fallback behavior.",
                    "lessons": [
                        {
                            "id": "l4m1-1",
                            "title": "Policy-aware Prompting",
                            "what_you_learn": "Embedding safety constraints and prohibited content handling.",
                            "hands_on": "Design prompts with explicit safety boundaries.",
                            "deliverable": "Safety prompt policy template.",
                        },
                        {
                            "id": "l4m1-2",
                            "title": "Adversarial Prompt Defense",
                            "what_you_learn": "Prompt injection patterns and resilience strategies.",
                            "hands_on": "Red-team 15 malicious prompts and harden your instructions.",
                            "deliverable": "Prompt defense test log.",
                        },
                    ],
                    "review_questions": [
                        "Can your prompt resist instruction override attempts?",
                        "Are unsafe outputs blocked with graceful fallbacks?",
                        "Do safety rules preserve legitimate utility?",
                    ],
                },
                {
                    "id": "l4m2",
                    "title": "Retrieval and Context Engineering",
                    "objective": "Design prompts that work with external knowledge and dynamic context.",
                    "duration_hours": 10,
                    "checkpoint_project": "Build a context-grounded answering flow with citation-style outputs.",
                    "lessons": [
                        {
                            "id": "l4m2-1",
                            "title": "Context Packaging",
                            "what_you_learn": "Structuring retrieved chunks for high-signal prompting.",
                            "hands_on": "Format mixed-source context into reliable prompt sections.",
                            "deliverable": "Context packaging standard.",
                        },
                        {
                            "id": "l4m2-2",
                            "title": "Grounded Answer Templates",
                            "what_you_learn": "Force outputs to cite and separate evidence from inference.",
                            "hands_on": "Create grounded QA prompts for policy documents.",
                            "deliverable": "Grounded output prompt template.",
                        },
                    ],
                    "review_questions": [
                        "Does the model separate facts from assumptions?",
                        "Is citation behavior consistent across responses?",
                        "Does irrelevant context reduce answer quality?",
                    ],
                },
                {
                    "id": "l4m3",
                    "title": "Observability and Monitoring",
                    "objective": "Track quality drift in real usage.",
                    "duration_hours": 7,
                    "checkpoint_project": "Set up prompt monitoring dashboard with alerting thresholds.",
                    "lessons": [
                        {
                            "id": "l4m3-1",
                            "title": "Telemetry Design",
                            "what_you_learn": "Logging prompt versions, outcomes, latency, and token use.",
                            "hands_on": "Define event schema for prompt telemetry.",
                            "deliverable": "Prompt observability schema.",
                        },
                        {
                            "id": "l4m3-2",
                            "title": "Drift Detection",
                            "what_you_learn": "Identifying regression, bias drift, and failure spikes.",
                            "hands_on": "Create drift rules and escalation runbook.",
                            "deliverable": "Prompt incident response playbook.",
                        },
                    ],
                    "review_questions": [
                        "Can you detect quality drops within 24 hours?",
                        "Is every production prompt traceable to a version?",
                        "Do alerts map to clear remediation steps?",
                    ],
                },
            ],
            "capstone": "Deploy a production prompt system with guardrails, retrieval grounding, and monitoring.",
        },
        {
            "id": "level-5",
            "level": "Industry Expert",
            "title": "Enterprise Strategy and Leadership",
            "duration_weeks": 4,
            "outcome": "Lead prompt engineering programs and set organizational standards.",
            "modules": [
                {
                    "id": "l5m1",
                    "title": "Prompt Architecture at Scale",
                    "objective": "Design org-wide prompt standards and reusable architectures.",
                    "duration_hours": 10,
                    "checkpoint_project": "Create enterprise prompt architecture blueprint.",
                    "lessons": [
                        {
                            "id": "l5m1-1",
                            "title": "Prompt System Architecture",
                            "what_you_learn": "Layered prompts, tool-calls, and orchestration patterns.",
                            "hands_on": "Map architecture for customer support and analytics copilots.",
                            "deliverable": "Architecture decision record.",
                        },
                        {
                            "id": "l5m1-2",
                            "title": "Cross-team Prompt Standards",
                            "what_you_learn": "Governance models for consistency and compliance.",
                            "hands_on": "Draft a prompt style guide for multi-team adoption.",
                            "deliverable": "Organization prompt standard v1.",
                        },
                    ],
                    "review_questions": [
                        "Can standards be applied by all teams consistently?",
                        "Does architecture support rapid iteration?",
                        "Are governance and innovation balanced?",
                    ],
                },
                {
                    "id": "l5m2",
                    "title": "Prompt Ops and ROI",
                    "objective": "Connect prompt engineering to business outcomes.",
                    "duration_hours": 9,
                    "checkpoint_project": "Build a quarterly prompt optimization roadmap with ROI model.",
                    "lessons": [
                        {
                            "id": "l5m2-1",
                            "title": "Business KPI Mapping",
                            "what_you_learn": "Tie prompt quality to conversion, productivity, and support metrics.",
                            "hands_on": "Define KPI tree for an AI feature launch.",
                            "deliverable": "Prompt KPI map.",
                        },
                        {
                            "id": "l5m2-2",
                            "title": "Experiment Portfolio Management",
                            "what_you_learn": "Prioritize prompt experiments by impact and risk.",
                            "hands_on": "Rank 20 prompt improvements using value-effort scoring.",
                            "deliverable": "Prompt experiment backlog.",
                        },
                    ],
                    "review_questions": [
                        "Which prompt changes drive measurable business lift?",
                        "Are low-value experiments pruned quickly?",
                        "Do teams align on outcome metrics?",
                    ],
                },
                {
                    "id": "l5m3",
                    "title": "Mentoring and Expert Practice",
                    "objective": "Operate as a principal-level prompt engineering expert.",
                    "duration_hours": 8,
                    "checkpoint_project": "Lead a live prompt clinic and produce organizational best-practice report.",
                    "lessons": [
                        {
                            "id": "l5m3-1",
                            "title": "Prompt Code Reviews",
                            "what_you_learn": "How to review prompts like production code.",
                            "hands_on": "Run peer reviews for 12 prompts and provide actionable feedback.",
                            "deliverable": "Prompt review checklist.",
                        },
                        {
                            "id": "l5m3-2",
                            "title": "Teaching Prompt Craft",
                            "what_you_learn": "Coaching frameworks and team enablement strategies.",
                            "hands_on": "Design a 2-hour internal workshop for non-technical teams.",
                            "deliverable": "Workshop kit and facilitation guide.",
                        },
                    ],
                    "review_questions": [
                        "Is your feedback specific and measurable?",
                        "Can mentees improve prompts in one iteration?",
                        "Do standards spread beyond the initial team?",
                    ],
                },
            ],
            "capstone": "Publish an enterprise prompt strategy and lead multi-team rollout.",
        },
    ],
    "final_certification": {
        "title": "Industry Expert Prompt Engineer",
        "requirements": [
            "Complete all level capstones.",
            "Pass final practical exam with minimum score 8.0/10.",
            "Submit one production-ready prompt system design.",
            "Present optimization and governance strategy to peer panel.",
        ],
    },
}
